In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
new=pd.read_csv('insurance.csv')

In [3]:
new

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
9      60  female  25.840         0     no  northwest  28923.13692
10     25    male  26.220         0     no  northeast   2721.32080
11     62  female  26.290         0    yes  southeast  27808.72510
12     23    male  34.400         0     no  southwest   1826.84300
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
15     19    male  24.600         1     no  southwest   1837.23700
16     52  female  30.780         1     no  northeast  10797.33620
17     23    male  23.845         0     no  northeast   2395.17155
18     56    male  40.300         0     no  southwest  10602.38500
19     30    male  35.300         0    yes  southwest  36837.46700
20     60  female  36.005         0     no  northeast  13228.84695
21     30  female  32.400         1     no  southwest   4149.73600
22     18    male  34.100         0     no  southeast   1137.01100
23     34  female  31.920         1    yes  northeast  37701.87680
24     37    male  28.025         2     no  northwest   6203.90175
25     59  female  27.720         3     no  southeast  14001.13380
26     63  female  23.085         0     no  northeast  14451.83515
27     55  female  32.775         2     no  northwest  12268.63225
28     23    male  17.385         1     no  northwest   2775.19215
29     31    male  36.300         2    yes  southwest  38711.00000
...   ...     ...     ...       ...    ...        ...          ...
1308   25  female  30.200         0    yes  southwest  33900.65300
1309   41    male  32.200         2     no  southwest   6875.96100
1310   42    male  26.315         1     no  northwest   6940.90985
1311   33  female  26.695         0     no  northwest   4571.41305
1312   34    male  42.900         1     no  southwest   4536.25900
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1315   18    male  28.310         1     no  northeast  11272.33139
1316   19  female  20.600         0     no  southwest   1731.67700
1317   18    male  53.130         0     no  southeast   1163.46270
1318   35    male  39.710         4     no  northeast  19496.71917
1319   39  female  26.315         2     no  northwest   7201.70085
1320   31    male  31.065         3     no  northwest   5425.02335
1321   62    male  26.695         0    yes  northeast  28101.33305
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1324   31    male  25.935         1     no  northwest   4239.89265
1325   61    male  33.535         0     no  northeast  13143.33665
1326   42  female  32.870         0     no  northeast   7050.02130
1327   51    male  30.030         1     no  southeast   9377.90470
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast

In [18]:
x=new.iloc[:,:6].values

In [19]:
x

array([[19, 'female', 27.9, 0, 'yes', 'southwest'],
       [18, 'male', 33.77, 1, 'no', 'southeast'],
       [28, 'male', 33.0, 3, 'no', 'southeast'],
       ...,
       [18, 'female', 36.85, 0, 'no', 'southeast'],
       [21, 'female', 25.8, 0, 'no', 'southwest'],
       [61, 'female', 29.07, 0, 'yes', 'northwest']], dtype=object)

In [16]:
y=new.iloc[:,6:].values

In [17]:
y

array([[16884.924 ],
       [ 1725.5523],
       [ 4449.462 ],
       ...,
       [ 1629.8335],
       [ 2007.945 ],
       [29141.3603]])

In [20]:
new.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

In [21]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [24]:
x[:,1]=LabelEncoder().fit_transform(x[:,1])
x[:,4]=LabelEncoder().fit_transform(x[:,4])
x[:,5]=LabelEncoder().fit_transform(x[:,5])

In [25]:
x

array([[19, 0, 27.9, 0, 1, 3],
       [18, 1, 33.77, 1, 0, 2],
       [28, 1, 33.0, 3, 0, 2],
       ...,
       [18, 0, 36.85, 0, 0, 2],
       [21, 0, 25.8, 0, 0, 3],
       [61, 0, 29.07, 0, 1, 1]], dtype=object)

In [26]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(categorical_features=[5])#categorical Features represents which column to be onehot encoded
x=oh.fit_transform(x).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [27]:
x

array([[ 0.  ,  0.  ,  0.  , ..., 27.9 ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , ..., 33.77,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , ..., 33.  ,  3.  ,  0.  ],
       ...,
       [ 0.  ,  0.  ,  1.  , ..., 36.85,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ..., 25.8 ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ..., 29.07,  0.  ,  1.  ]])

In [28]:
x.shape

(1338, 9)

In [29]:
y.shape

(1338, 1)

In [30]:
x=x[:,1:]

In [31]:
x

array([[ 0.  ,  0.  ,  1.  , ..., 27.9 ,  0.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , ..., 33.77,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ..., 33.  ,  3.  ,  0.  ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 36.85,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , ..., 25.8 ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ..., 29.07,  0.  ,  1.  ]])

In [32]:
x.shape

(1338, 8)

In [33]:
from sklearn.model_selection import train_test_split              
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [34]:
x_train

array([[ 0.  ,  0.  ,  1.  , ..., 34.1 ,  4.  ,  1.  ],
       [ 0.  ,  1.  ,  0.  , ..., 34.43,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ..., 36.67,  2.  ,  1.  ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 25.08,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ..., 35.53,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  , ..., 18.5 ,  1.  ,  0.  ]])

In [35]:
from sklearn.linear_model import LinearRegression
mr = LinearRegression()

In [41]:
mr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [42]:
y_predict =mr.predict(x_test)

In [43]:
y_predict

array([[1.11699271e+04],
       [9.48670909e+03],
       [3.81811231e+04],
       [1.62663133e+04],
       [6.91464801e+03],
       [3.96348488e+03],
       [1.57939691e+03],
       [1.43852566e+04],
       [9.01257970e+03],
       [7.50846068e+03],
       [4.49176728e+03],
       [1.02795839e+04],
       [8.80129751e+03],
       [3.79802013e+03],
       [2.79262010e+04],
       [1.07151158e+04],
       [1.12889756e+04],
       [6.10501768e+03],
       [8.24104117e+03],
       [2.71445089e+04],
       [3.36440910e+04],
       [1.43551043e+04],
       [1.17372043e+04],
       [3.21374335e+04],
       [4.17005913e+03],
       [9.25496051e+03],
       [1.08433751e+03],
       [9.80417085e+03],
       [3.77104596e+03],
       [1.04318587e+04],
       [9.00931722e+03],
       [4.00749509e+04],
       [1.56889543e+04],
       [1.38794545e+04],
       [2.47597127e+04],
       [5.16638285e+03],
       [1.26109277e+04],
       [3.07691018e+04],
       [3.35498325e+04],
       [3.67154946e+03],


In [45]:
mr.predict([[19,1,27.9,0,1,2,7,8]])

array([[153612.72768855]])